USE [lottery-db];
GO

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMNPROPERTY(OBJECT_ID('countries'), COLUMN_NAME, 'IsIdentity') AS Is_Identity
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'countries'
ORDER BY ORDINAL_POSITION;
